In [1]:
with open('2020_day6.txt', 'r') as f:
    data = f.readlines()

In [2]:
data[0].rstrip('\n')

'lqhksfnerg'

In [3]:
l = ''
l = l + 'ac'
l = l + 'ab'
l = l + 'abe'
l = l + 'abf'
l = l + 'azq'
q=set(l)
print(q)
len(q)

{'z', 'q', 'a', 'e', 'f', 'c', 'b'}


7

In [4]:
q = set()
count_list = []
i = 0
l = ''

while i < len(data)-1:
#    print('i: ', i, data[i])
    l = l + data[i].rstrip('\n')
#    print(l)
    if data[i+1] == '\n':
        count_list.append(len(set(l)))
#        print(len(set(l)), set(l))
        l = ''
    i += 1  

print('part 1:', sum(count_list))

part 1: 6297


## part 2

In [5]:
import numpy as np
q = 'abcdefghijklmnopqrstuvwxyzT'
tallies = [0]*27
tallies = np.array(tallies)
tallies

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [6]:
for i in range(0,4):  # loop 4 times
    tallies[2] += 1
tallies

array([0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [7]:
l = 'acegikmoqsuwy'
print(list(l))
for a in list(l):
    x = q.find(a)
#    print(x)
    tallies[x]  += 1  # add 1 to the position if a letter is found
tallies[26] += 1 # add 1 for each person's answers
print(tallies)


['a', 'c', 'e', 'g', 'i', 'k', 'm', 'o', 'q', 's', 'u', 'w', 'y']
[1 0 5 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [8]:
def update_tallies(l):  # for each person's answer set
    for a in list(l):
        x = q.find(a)  # find position of a in q
    #    print(x)
        tallies[x]  += 1  # add 1 to the position if a letter is found
    tallies[26] += 1 # add 1 for each person's answers
    return tallies[26] # return the total of people so far


In [9]:
l = 'acegikmoqsuwy'
print(list(l))
update_tallies(l)
print(tallies)

['a', 'c', 'e', 'g', 'i', 'k', 'm', 'o', 'q', 's', 'u', 'w', 'y']
[2 0 6 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]


In [10]:
print(tallies)

[2 0 6 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]


In [11]:
# get total of questions everyone answers 'yes' per group 
def q_count(tallies):
    q = 0
    # update q comparing value of each question/key to T
    for i in range(0, 26):
        if tallies[i] == tallies[26]:
            q += 1
    return q


In [12]:
sum_of_count = 0
sum_of_count = sum_of_count + q_count(tallies)
sum_of_count

12

In [ ]:
# initialize variables
sum_of_count = 0      # cumulative sum for all groups
count        = 0      # count of questions per group
i            = 0      # to iterate through data
tallies      = [0]*27 # to store tallies for each person
q = 'abcdefghijklmnopqrstuvwxyzT'

# loop through all data
while i < len(data)-1:
#    print('i: ', i, data[i])
    l = data[i].rstrip('\n')
    # update tallies for each person
    if l!='':
        update_tallies(l)
#        print(l)
#        print(tallies)
        
    # if next line is blank/end of one group
    if data[i+1] == '\n': 
        # get count of questions that everyone answered 'yes'
        count = q_count(tallies)
        # cumulative total for groups so far
        sum_of_count = sum_of_count + count
#        print('cumulative sum of count:', sum_of_count)
        
        #reset for next group
        tallies = [0]*27
        count   = 0
    i += 1  # to process next line
    


In [14]:
print('part 2:', sum_of_count)

part 2: 3158
