In [1]:
# 2020 day 13 part 1
# Examples
#earliest = 939
#buses = [7,13,59,31,19]

earliest = 1006605
buses = [19,37,883,23,13,17,797,41,29]
buses


[19, 37, 883, 23, 13, 17, 797, 41, 29]

In [2]:
# calculate min missed bus at earliest available time
miss = []
for bus in buses:
    miss.append(earliest % bus)
    print('bus',bus, 'miss', earliest % bus)
print(miss)    

bus 19 miss 4
bus 37 miss 20
bus 883 miss 868
bus 23 miss 10
bus 13 miss 2
bus 17 miss 1
bus 797 miss 791
bus 41 miss 14
bus 29 miss 15
[4, 20, 868, 10, 2, 1, 791, 14, 15]


In [3]:
# calculate wait time for next bus
wait = []
for i in range(0, len(buses)):
    wait.append(buses[i]-miss[i])
print(wait)

[15, 17, 15, 13, 11, 16, 6, 27, 14]


In [6]:
# answer wait time of the next soonest bus times the bus number
for i in range(0, len(wait)):
    if wait[i] == min(wait):
        print(buses[i]*wait[i])

4782


In [7]:
max(buses)

883

In [8]:
# 2020 day 13 part 1
# Examples
#earliest = 939
#buses = [7,13,59,31,19]

# inputs
earliest = 1006605
l = '19,x,x,x,x,x,x,x,x,x,x,x,x,37,x,x,x,x,x,883,x,x,x,x,x,x,x,23,x,x,x,x,13,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,x,x,797,x,x,x,x,x,x,x,x,x,41,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,29'
l = list(l.split(','))
buses = [int(x) for x in l if x !='x']

# calculate min missed bus at earliest available time
miss = []
wait = []
for bus in buses:
    miss.append(earliest % bus)
    wait.append(bus - earliest % bus)
#    print('bus',bus, 'miss', earliest % bus, 'wait', bus - earliest % bus)

# answer wait time of the next soonest bus times the bus number
for i in range(0, len(wait)):
    if wait[i] == min(wait):
        print('answer:', buses[i]*wait[i])

    

answer: 4782


In [32]:
# part 2

# Examples
# The earliest timestamp that matches the lists:
l1 = '17,x,13,19'      # is 3417.
l2 = '67,7,59,61'      # first occurs at timestamp 754018.
l3 = '67,x,7,59,61'    # first occurs at timestamp 779210.
l4 = '67,7,x,59,61'    # first occurs at timestamp 1261476.
l5 = '1789,37,47,1889' # first occurs at timestamp 1202161486.
L1_earliest = 3417-100
L2_earliest = 754018-100
L3_earliest = 779210-100
L4_earliest = 1261476-100
L5_earliest = 1202161486-100
L1 = list(l1.split(','))
L2 = list(l2.split(','))
L3 = list(l3.split(','))
L4 = list(l4.split(','))
L5 = list(l5.split(','))

# inputs
L_earliest = 100000000000000
l = '19,x,x,x,x,x,x,x,x,x,x,x,x,37,x,x,x,x,x,883,x,x,x,x,x,x,x,23,x,x,x,x,13,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,x,x,797,x,x,x,x,x,x,x,x,x,41,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,29'
L = list(l.split(','))


In [16]:
print(L)

['19', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '37', 'x', 'x', 'x', 'x', 'x', '883', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '23', 'x', 'x', 'x', 'x', '13', 'x', 'x', 'x', '17', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '797', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '41', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '29']


In [28]:
# create bus schedules
import numpy as np

def buses_offsets(L):
    buses = []
    offsets = []
    j = 0
    for i in L:
        if i !='x':
            buses.append(i)
            offsets.append(j)
        j+=1
    buses = np.array(buses, dtype = int)
    offsets = np.array(offsets, dtype = int)
    return(buses, offsets)


In [29]:
buses, offsets = buses_offsets(L)
print(L)
print(buses)
print(offsets)


['19', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '37', 'x', 'x', 'x', 'x', 'x', '883', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '23', 'x', 'x', 'x', 'x', '13', 'x', 'x', 'x', '17', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '797', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '41', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', '29']
[ 19  37 883  23  13  17 797  41  29]
[ 0 13 19 27 32 36 50 60 79]


In [30]:
buses, offsets = buses_offsets(L1)
print(L1)
print(buses)
print(offsets)

['17', 'x', '13', '19']
[17 13 19]
[0 2 3]


In [55]:
# find_t 
def find_t(t, buses, offsets):
    # initialize
    flag = True 
    while flag:
#        print(t)
        # find next departures
        next_depts[0] = t + buses[0] - t%buses[0]
        for i in range(1, len(buses)):  
            next_depts[i] = next_depts[0] + buses[i] - next_depts[0]%buses[i]       
#        print('t:', t, next_depts)

        # check if all buses depart at their required offsets       
        for i in range(1, len(next_depts)):
            # flag to exit while loop when flag = True fo all buses
            flag = flag and next_depts[i] - next_depts[0] == offsets[i]  

        if flag:
            break
        elif flag == False: # not all buses depart at offsets
            # set t for next while loop after dep time of the latest bus
            t = max(next_depts)
#            print('next t:', t)
#            time.sleep(5)
            flag = True # reset
    return(t, next_depts)

# find t for answer, where all buses are departing at the required offset time
# initialize variables

t_answer = 1871350426152655
t_closer = 1871350426000000

offsets = []
buses, offsets = buses_offsets(L5)
next_depts = np.zeros(len(buses), dtype = int)

# find_t
t, next_depts = find_t(L5_earliest, buses, offsets1)

print(buses)
print('part 2:  t:', t, 'next departures:', next_depts)



KeyboardInterrupt: 

In [ ]:
#!/usr/bin/python3

# one-line python solution for part 1
# from https://www.reddit.com/user/teksimian/
# https://www.reddit.com/r/adventofcode/comments/kc4njx/2020_day_13_solutions/

import math

print(math.prod(sorted(list(zip(list( 
    map(lambda x: (math.ceil((int(str(open("input.txt", mode='r').read()).strip().split("\n")[0]) / x)) * x) 
        - int(str(open("input.txt", mode='r').read()).strip().split("\n")[0]), 
        list(map(int, list(filter(lambda x: x != 'x', str(open("input.txt", mode='r').read()).strip().split("\n")[1].split(","))))))),
                                list(map(int, list(filter(lambda x: x != 'x', str(open("input.txt", mode='r').read()).strip().split("\n")[1].split(",")))))))).pop(0)))

In [56]:
# part 2 - complete

import numpy as np

# Examples
# The earliest timestamp that matches the lists:
l1 = '17,x,13,19'      # is 3417.
l2 = '67,7,59,61'      # first occurs at timestamp 754018.
l3 = '67,x,7,59,61'    # first occurs at timestamp 779210.
l4 = '67,7,x,59,61'    # first occurs at timestamp 1261476.
l5 = '1789,37,47,1889' # first occurs at timestamp 1202161486.
L1_earliest = 3417-100
L2_earliest = 754018-100
L3_earliest = 779210-100
L4_earliest = 1261476-100
L5_earliest = 1202161486-100
L1 = list(l1.split(','))
L2 = list(l2.split(','))
L3 = list(l3.split(','))
L4 = list(l4.split(','))
L5 = list(l5.split(','))

# inputs
L_earliest = 100000000000000
l = '19,x,x,x,x,x,x,x,x,x,x,x,x,37,x,x,x,x,x,883,x,x,x,x,x,x,x,23,x,x,x,x,13,x,x,x,17,x,x,x,x,x,x,x,x,x,x,x,x,x,797,x,x,x,x,x,x,x,x,x,41,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,x,29'
L = list(l.split(','))

# create bus schedules

def buses_offsets(L):
    buses = []
    offsets = []
    j = 0
    for i in L:
        if i !='x':
            buses.append(i)
            offsets.append(j)
        j+=1
    buses = np.array(buses, dtype = int)
    offsets = np.array(offsets, dtype = int)
    return(buses, offsets)

# find_t 
def find_t(t, buses, offsets):
    # initialize
    flag = True 
    while flag:

        # find next departures
        next_depts[0] = t + buses[0] - t%buses[0]
        for i in range(1, len(buses)):  
            next_depts[i] = next_depts[0] + buses[i] - next_depts[0]%buses[i]       

        # check if all buses depart at their required offsets       
        for i in range(1, len(next_depts)):
            # flag to exit while loop when flag = True fo all buses
            flag = flag and next_depts[i] - next_depts[0] == offsets[i]  

        if flag:
            break
        elif flag == False: # not all buses depart at offsets
            # set t for next while loop after dep time of the latest bus
            t = max(next_depts)
            flag = True # reset
    return(t, next_depts)

# find t for answer, where all buses are departing at the required offset time
# initialize variables
offsets = []
buses, offsets = buses_offsets(L5)
next_depts = np.zeros(len(buses), dtype = int)

# find_t
t, next_depts = find_t(L5_earliest, buses, offsets)

# print results
print('buses:', buses, 'offsets:', offsets)
print('part 2: t with departures at required offsets:', next_depts)



buses: [1789   37   47 1889] offsets: [0 1 2 3]
part 2: t with departures at required offsets: [1202161486 1202161487 1202161488 1202161489]
