In [1]:
with open('2020_day6.txt', 'r') as f:
    data = f.readlines()

In [2]:
data[0].rstrip('\n')

'lqhksfnerg'

In [3]:
l = ''
l = l + 'ac'
l = l + 'ab'
l = l + 'abe'
l = l + 'abf'
l = l + 'azq'
q=set(l)
print(q)
len(q)

{'z', 'q', 'a', 'e', 'f', 'c', 'b'}


7

In [4]:
q = set()
count_list = []
i = 0
l = ''

while i < len(data)-1:
#    print('i: ', i, data[i])
    l = l + data[i].rstrip('\n')
#    print(l)
    if data[i+1] == '\n':
        count_list.append(len(set(l)))
#        print(len(set(l)), set(l))
        l = ''
    i += 1  

print('part 1:', sum(count_list))

part 1: 6297


## part 2

In [5]:
import numpy as np
q = 'abcdefghijklmnopqrstuvwxyzT'
tallies = [0]*27
tallies = np.array(tallies)
tallies

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [6]:
for i in range(0,4):  # loop 4 times
    tallies[2] += 1
tallies

array([0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0])

In [7]:
l = 'acegikmoqsuwy'
print(list(l))
for a in list(l):
    x = q.find(a)
#    print(x)
    tallies[x]  += 1  # add 1 to the position if a letter is found
tallies[26] += 1 # add 1 for each person's answers
print(tallies)


['a', 'c', 'e', 'g', 'i', 'k', 'm', 'o', 'q', 's', 'u', 'w', 'y']
[1 0 5 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [8]:
def update_tallies(l):  # for each person's answer set
    for a in list(l):
        x = q.find(a)  # find position of a in q
    #    print(x)
        tallies[x]  += 1  # add 1 to the position if a letter is found
    tallies[26] += 1 # add 1 for each person's answers
    return tallies[26] # return the total of people so far


In [9]:
l = 'acegikmoqsuwy'
print(list(l))
update_tallies(l)
print(tallies)

['a', 'c', 'e', 'g', 'i', 'k', 'm', 'o', 'q', 's', 'u', 'w', 'y']
[2 0 6 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]


In [10]:
print(tallies)

[2 0 6 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2 0 2]


In [11]:
# get total of questions everyone answers 'yes' per group 
def q_count(tallies):
    q = 0
    # update q comparing value of each question/key to T
    for i in range(0, 26):
        if tallies[i] == tallies[26]:
            q += 1
    return q


In [12]:
sum_of_count = 0
sum_of_count = sum_of_count + q_count(tallies)
sum_of_count

12

In [13]:
# initialize variables
sum_of_count = 0      # cumulative sum for all groups
count        = 0      # count of questions per group
i            = 0      # to iterate through data
tallies      = [0]*27 # to store tallies for each person
q = 'abcdefghijklmnopqrstuvwxyzT'

# loop through all data
while i < len(data)-1:
#    print('i: ', i, data[i])
    l = data[i].rstrip('\n')
    # update tallies for each person
    if l!='':
        update_tallies(l)
        print(l)
        print(tallies)
        
    # if next line is blank/end of one group
    if data[i+1] == '\n': 
        # get count of questions that everyone answered 'yes'
        count = q_count(tallies)
        # cumulative total for groups so far
        sum_of_count = sum_of_count + count
        print('cumulative sum of count:', sum_of_count)
        
        #reset for next group
        tallies = [0]*27
        count   = 0
    i += 1  # to process next line
    


lqhksfnerg
[0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
negsc
[0, 0, 1, 0, 2, 1, 2, 1, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 0, 0, 0, 0, 0, 0, 0, 2]
snage
[1, 0, 1, 0, 3, 1, 3, 1, 0, 0, 1, 1, 0, 3, 0, 0, 1, 1, 3, 0, 0, 0, 0, 0, 0, 0, 3]
engs
[1, 0, 1, 0, 4, 1, 4, 1, 0, 0, 1, 1, 0, 4, 0, 0, 1, 1, 4, 0, 0, 0, 0, 0, 0, 0, 4]
sneg
[1, 0, 1, 0, 5, 1, 5, 1, 0, 0, 1, 1, 0, 5, 0, 0, 1, 1, 5, 0, 0, 0, 0, 0, 0, 0, 5]
cumulative sum of count: 4
ctfzrdbsapql
[1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1]
srldfatzqcpb
[2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2]
qsntlprfdbza
[3, 3, 2, 3, 0, 3, 0, 0, 0, 0, 0, 3, 0, 1, 0, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 3, 3]
ldptswouqbxzafr
[4, 4, 2, 4, 0, 4, 0, 0, 0, 0, 0, 4, 0, 1, 1, 4, 4, 4, 4, 4, 1, 0, 1, 1, 0, 4, 4]
cumulative sum of count: 15
ncjolhqfbp
[0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
gphonqbflxj
[0, 2, 1, 0, 0

cumulative sum of count: 874
oaustqdifyxepkrwh
[1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1]
kbcvmrjn
[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2]
cumulative sum of count: 876
uqv
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1]
qrvw
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 2]
qv
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 0, 0, 1, 3, 1, 0, 0, 0, 3]
vqtmu
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 1, 2, 4, 1, 0, 0, 0, 4]
qv
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 5, 1, 0, 1, 2, 5, 1, 0, 0, 0, 5]
cumulative sum of count: 878
lo
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
l
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
l
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
t
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,

[3, 3, 0, 1, 3, 0, 3, 3, 0, 3, 3, 0, 3, 3, 3, 0, 3, 3, 0, 3, 3, 1, 3, 3, 3, 0, 3]
cumulative sum of count: 1015
lqdiban
[1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
ifbazln
[2, 2, 0, 1, 0, 1, 0, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2]
bafzinl
[3, 3, 0, 1, 0, 2, 0, 0, 3, 0, 0, 3, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 3]
ifsbanl
[4, 4, 0, 1, 0, 3, 0, 0, 4, 0, 0, 4, 0, 4, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 2, 4]
cumulative sum of count: 1020
dovkxjylabqmtizw
[1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1]
pawvoxdmbyizqtj
[2, 2, 0, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2]
vwubiayopgxcjzqdtm
[3, 3, 1, 3, 0, 0, 1, 0, 3, 3, 1, 1, 3, 0, 3, 2, 3, 0, 0, 3, 1, 3, 3, 3, 3, 3, 3]
qbjtvowdnzsixamy
[4, 4, 1, 4, 0, 0, 1, 0, 4, 4, 1, 1, 4, 1, 4, 2, 4, 0, 1, 4, 1, 4, 4, 4, 4, 4, 4]
cumulative sum of count: 1034
ykpusjaqclowb
[1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,

[1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1]
sidlbyakwrhvgmjoef
[2, 2, 0, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 1, 2]
cumulative sum of count: 1407
q
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]
q
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2]
q
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
cumulative sum of count: 1408
jofkmbcunaxet
[1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1]
elqngabhskmy
[2, 2, 1, 0, 2, 1, 1, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2]
wkmxacenib
[3, 3, 2, 0, 3, 1, 1, 1, 1, 1, 3, 1, 3, 3, 1, 0, 1, 0, 1, 1, 1, 0, 1, 2, 1, 0, 3]
cumulative sum of count: 1414
ezfpogadrbulys
[1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1]
sbamgenyopfzu
[2, 2, 0, 1, 2, 2, 2, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 1, 2, 0, 2, 0, 0, 0, 2, 2, 2

hcgasrpewnoktq
[3, 0, 3, 0, 3, 0, 3, 3, 0, 0, 3, 0, 0, 3, 3, 3, 3, 3, 3, 3, 0, 1, 3, 0, 1, 1, 3]
tkewponscaqhrg
[4, 0, 4, 0, 4, 0, 4, 4, 0, 0, 4, 0, 0, 4, 4, 4, 4, 4, 4, 4, 0, 1, 4, 0, 1, 1, 4]
cumulative sum of count: 1869
bjrsxkeiucnpoz
[0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1]
xrkczspbfeu
[0, 2, 2, 0, 2, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 2, 0, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2]
kqcuytdsrhvgplbxa
[1, 3, 3, 1, 2, 1, 1, 1, 1, 1, 3, 1, 0, 1, 1, 3, 1, 3, 3, 1, 3, 1, 0, 3, 1, 2, 3]
cumulative sum of count: 1877
at
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1]
ae
[2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2]
cumulative sum of count: 1878
x
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
x
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 2]
v
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 3]
x
[

cumulative sum of count: 2239
quxomeysk
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1]
uqtokyxsm
[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2, 0, 2]
yqohxbkm
[0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 3, 0, 3, 0, 3, 0, 3, 0, 2, 1, 2, 0, 0, 3, 3, 0, 3]
uyoqkaxm
[1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 4, 0, 4, 0, 4, 0, 4, 0, 2, 1, 3, 0, 0, 4, 4, 0, 4]
cumulative sum of count: 2245
br
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]
rbi
[0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2]
brj
[0, 3, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 3]
cumulative sum of count: 2247
paqhkzmcwfrsiubtvjnx
[1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1]
zktiqbucarpwnxmyhj
[2, 2, 2, 0, 0, 1, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2]
aikmgtyucrjnpqwhxzb
[3, 3, 3, 0, 0, 1, 1, 3, 3, 3, 3, 0, 3, 3, 0, 3, 3, 3, 1, 3, 3,

[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1]
wheyaut
[2, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 2, 0, 2, 0, 2, 0, 2]
ateuyw
[3, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 3, 3, 0, 3, 0, 3, 0, 3]
awyeut
[4, 0, 0, 0, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 4, 4, 0, 4, 0, 4, 0, 4]
cumulative sum of count: 2563
swuaon
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1]
usnwao
[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 0, 2]
cumulative sum of count: 2569
udcyfksltzeqb
[0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1]
bkuycfstdqzel
[0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 0, 2, 2, 2]
cumulative sum of count: 2582
gjmbfxieklohpc
[0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]
oglhiuyxjekcmfpr
[0, 1, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 0, 0, 1, 0, 0, 2, 1, 

In [14]:
print('part 2:', sum_of_count)

part 2: 3158
